version = 0.1

[default]
region = "eu-west-3"
capabilities = "CAPABILITY_IAM"

[preprod.deploy.parameters]
stack_name = "shoplist-preprod"
parameter_overrides = "Env=preprod FunctionName=shoplist-authorizer-preprod AppName=shoplist DeployPrefType=AllAtOnce"
no_confirm_changeset = true

[prod.deploy.parameters]
stack_name = "shoplist-prod"
parameter_overrides = "Env=prod FunctionName=shoplist-authorizer-prod AppName=shoplist DeployPrefType=Canary10Percent5Minutes"
no_confirm_changeset = true